---
###
# Check https://github.com/ray-rock/containarr/wiki for more information/documentation. If you run into an issue
# not covered in the comments or documents, please open a discussion or an issue at https://github.com/ray-rock/containarr
###
version: '3.8'

###
# These are docker volumes. Most people only need a single data volume. This volume can be local, or somewhere else... Example SMB config provided below.
# If you're on a gnu/linux distro, you may need to install cifs-utils. See https://github.com/ray-rock/containarr/wiki for more info.
###
volumes:
    data:
    ### PROVIDE SPECIFIC EXAMPLES FOR SMB
    # downloads: # Use this configuration if you know what you're doing! The default
    #     # driver_opts: # use driver_opts if you're going to configure SMB or something...
    #     #     type: <CONFIGURE>
    #     #     o: "<CONFIGURE>"
    #     #     device: "<CONFIGURE>"
    # media:
    #     # driver_opts:
    #     #     type: <CONFIGURE>
    #     #     o: "<CONFIGURE>"
    #     #     device: "<CONFIGURE>"

services:
    ###
    # This is the portal where you access all of your arr!
    ###
    portal:
        image: localhost.local/containarr/portal
        container_name: portal
        build: ./build/nginx/.
        network_mode: "service:gluetun"

    ###
    # This is the VPN provider. Anything routed through this will be tunneled through your VPN.
    ###
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        env_file:
            - config/gluetun/vpn-config.env                        # See https://github.com/qdm12/gluetun/wiki for info on configuring your vpn.
        ports:
            - 80:80         #nginx reverse proxy
            #- 8080:8080   #qbittorrent
            #- 8989:8989   #sonarr
            #- 7878:7878   #radarr
            #- 9696:9696   #prowlarr
            #- 8787:8787   #readarr
            #- 8686:8686   #lidarr
            #- 9117:9117   #jackett
            #- 6595:6595   #deemix
        restart: always

    qbittorrent:
        restart: always
        network_mode: "service:gluetun"
        image: lscr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=2500
            - PGID=2500
            - UMASK=022
            - UMASK_SET=022
            - TZ=UTC
            - WEBUI_PORT=8080
        volumes:
            - ./config/qbt:/config
            - data:/downloads

    deemix:
        restart: always
        network_mode: "service:gluetun"
        image: registry.gitlab.com/bockiii/deemix-docker
        container_name: Deemix
        environment:
            - PUID=2500
            - PGID=2500
            - UMASK_SET=022
            - TZ=UTC
            - DEEMIX_SINGLE_USER=true
        volumes:
            - ./config/deemix:/config
            - data:/downloads

    sonarr:
        restart: unless-stopped
        network_mode: "service:gluetun"
        image: lscr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=2500
            - PGID=2500
            - UMASK=022
            - UMASK_SET=022
            - TZ=UTC
        volumes:
            - ./config/sonarr:/config
            - data:/media


    radarr:
        restart: always
        network_mode: "service:gluetun"
        image: lscr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=2500
            - PGID=2500
            - UMASK=022
            - UMASK_SET=022
            - TZ=UTC
        volumes:
            - ./config/radarr:/config
            - data:/media

    prowlarr:
        restart: always
        network_mode: "service:gluetun"
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=2500
            - PGID=2500
            - UMASK=022
            - UMASK_SET=022
            - TZ=UTC
        volumes:
            - ./config/prowlarr:/config

    # readarr:
    #     restart: unless-stopped
    #     network_mode: "service:gluetun"
    #     image: ghcr.io/linuxserver/readarr:nightly
    #     container_name: readarr
    #     environment:
    #         - PUID=2500
    #         - PGID=2500
    #         - UMASK=022
    #         - UMASK_SET=022
    #         - TZ=UTC
    #     volumes:
    #         - ./config/readarr:/config
    #         - media:/media
    #         - downloads:/downloads:ro

    # jackett:
    #     restart: unless-stopped
    #     network_mode: "service:gluetun"
    #     image: lscr.io/linuxserver/jackett
    #     container_name: jackett
    #     environment:
    #         - PUID=2500
    #         - PGID=2500
    #         - UMASK=022
    #         - UMASK_SET=022
    #         - TZ=UTC
    #         - AUTO_UPDATE=true #optional
    #     volumes:
    #         - ./config/jackett:/config
